//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63130480.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoQL { get; set; }
        public string TenQL { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string AnhQL { get; set; }
        public string SoDienThoaiQL { get; set; }
        public string Email { get; set; }
        public Nullable<bool> PhanQuyen { get; set; }
    }
}
