//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63130480.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MoTaSP { get; set; }
        public string DonViTinh { get; set; }
        public string AnhSanPham { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string MaLoaiSP { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
